language: rust
sudo: true
dist: trusty
cache: cargo

install:
  - wget http://archive.ubuntu.com/ubuntu/pool/universe/c/capnproto/libcapnp-0.5.3_0.5.3-2ubuntu1_amd64.deb
  - wget http://archive.ubuntu.com/ubuntu/pool/universe/c/capnproto/capnproto_0.5.3-2ubuntu1_amd64.deb
  - sudo dpkg -i libcapnp-0.5.3_0.5.3-2ubuntu1_amd64.deb capnproto_0.5.3-2ubuntu1_amd64.deb
  - rustup component add rustfmt-preview

script:
  - cargo test --verbose
  - cargo fmt -- --check
