language: rust
dist: bionic
cache: cargo

os:
  - windows
  - linux
  - osx

matrix:
  include:
    - name: "Clippy Linux"
      os: linux
      env: CLIPPY=true
      if: tag IS NOT present

    - name: "Clippy OSX"
      os: osx
      env: CLIPPY=true
      if: tag IS NOT present

    - name: "Clippy Windows"
      os: windows
      env: CLIPPY=true
      if: tag IS NOT present

    - name: "Rustfmt"
      os: linux
      env: RUSTFMT=true
      if: tag IS NOT present

addons:
  apt:
    packages:
      - capnproto
  homebrew:
    packages:
      - capnp
    update: true

install: ci/install.sh
script: ci/script.sh
