language: rust
dist: bionic
cache: cargo

matrix:
  include:
    - os: windows
    - os: linux

addons:
  apt:
    packages:
      - capnproto

install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install capnproto; fi
  - rustup component add rustfmt

script:
  - cargo test --verbose
  - cargo fmt --all -- --check
