# Required variables for release publishing:
# GITHUB_TOKEN - GitHub token
# BINTRAY_USER - Bintray username
# BINTRAY_TOKEN - Bintray token

language: rust
dist: xenial
os:
  - windows
  - linux
  - osx

matrix:
  fast_finish: true
  include:
    - name: "Rustfmt"
      os: linux
      env: RUSTFMT=true
      if: tag IS NOT present

    - name: "Linux Clippy"
      os: linux
      env: CLIPPY=true
      if: tag IS NOT present

    - name: "OSX Clippy"
      os: osx
      env: CLIPPY=true
      if: tag IS NOT present

    - name: "Windows Clippy"
      os: windows
      env: CLIPPY=true
      if: tag IS NOT present

addons:
  apt:
    packages:
      - capnproto
  homebrew:
    packages:
      - capnp
    update: true

before_install:
  # Hack. gcc crashes on Travis when tries to compile lz4-sys
  - if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then rustup default stable-x86_64-pc-windows-msvc ; fi
install: ci/install.sh
script: ci/script.sh
before_deploy: ci/before_deploy.sh

deploy:
  - provider: releases
    api-key: ${GITHUB_TOKEN}
    file_glob: true
    file: target/deploy/*
    skip_cleanup: true
    on:
      tags: true
  - provider: bintray
    file: bintray-descriptor.json
    user: ${BINTRAY_USER}
    key: ${BINTRAY_TOKEN}
    skip_cleanup: true
    on:
      condition: ${TRAVIS_OS_NAME} = linux
      tags: true
