version: '{branch}-{build}'

install:
  - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-nightly-i686-pc-windows-gnu.exe'
  - ps: Start-FileDownload 'https://wixsharp.codeplex.com/downloads/get/1441782' WixSharp.7z
  - rust-nightly-i686-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - 7z.exe x WixSharp.7z -oWixSharp
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin;C:\MINGW\bin
  - SET WIXSHARP_DIR=%APPVEYOR_BUILD_FOLDER%\WixSharp\
  - rustc -V
  - cargo -V
  - git submodule update --init --recursive

build: false

test_script:
  - cargo test
  - cargo build --release
  - %WIXSHARP_DIR%\cscs.exe wixcs\setup.cs
