version: '{branch}-{build}'

build: false

environment:
  matrix:
#  - target: i686
  - target: x86_64

install:
- ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-$env:target-pc-windows-gnu.exe"
- ps: Start-FileDownload "https://static.bozaro.ru/x86_64-4.9.2-release-win32-seh-rt_v4-rev2.7z" mingw64.7z
- ps: Start-FileDownload "https://static.bozaro.ru/WixSharp.1.0.10.0.7z" WixSharp.7z
- rust-nightly-%TARGET%-pc-windows-gnu.exe   /VERYSILENT /NORESTART /DIR="%APPVEYOR_BUILD_FOLDER%\rust-%TARGET%"
- 7z.exe x WixSharp.7z -oWixSharp > nul
- 7z.exe x mingw64.7z > nul
- SET WIXSHARP_DIR=%APPVEYOR_BUILD_FOLDER%\WixSharp\
- SET MINGW_DIR=%APPVEYOR_BUILD_FOLDER%\mingw64\
- git submodule update --init --recursive

test_script:
- SET PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\rust-%TARGET%\bin;%MINGW_DIR%\bin;%WIXSHARP_DIR%
- rustc -V
- cargo -V
- cargo test
- cargo build --release
- cscs.exe wixcs\setup.cs
- nuget pack target\octobuild.nuspec -OutputDirectory target

artifacts:
- path: target/octobuild-*.msi
- path: target/octobuild-*.nupkg

deploy:
- provider: GitHub
  auth_token:
    secure: kDcv8Gxce2mGLKoZF9usWBmDzlUxxGLidDzKKehtPAx+m/Fbwpb7TLqbsUn8ecfv
  on:
    appveyor_repo_tag: true
  draft: false
  prerelease: false
- provider: NuGet
  server: http://chocolatey.org/
  api_key:
    secure: 5tG16DzbxdonFS7/jYYidxVgIA8QogBVx7u0TYvikAhygXezrVWn1JKAihEnM5D7
  artifact: /.*\.nupkg/
- provider: NuGet
  server: https://www.myget.org/
  api_key:
    secure: 8Xgud8TmDRF6fW3jZSI16SsDFPyYh8S/5HUCpHmeEV793APr4WT3xwFUu9HlM+eY
  artifact: /.*\.nupkg/
