[package]
name = "octobuild"
version = "0.0.2"
authors = [ "Artem V. Navrotskiy <bozaro@users.noreply.github.com>" ]

[dependencies.lz4-rs]
git = "https://github.com/bozaro/lz4-rs.git"

[dependencies.xml-rs]
version = "*"

[dependencies.uuid]
version = "*"

[dependencies.winapi]
version = "*"

[dependencies.advapi32-sys]
version = "*"
