[package]
name = "octobuild"
build = "src/build.rs"
version = "0.1.13"
authors = [ "Artem V. Navrotskiy <bozaro@users.noreply.github.com>" ]

[profile.bench]
debug = true

[[bin]]
name = "octo_builder"

[[bin]]
name = "octo_client"

[[bin]]
name = "octo_cl"

[[bin]]
name = "octo_clang"

[[bin]]
name = "octo_coordinator"

[[bin]]
name = "xgConsole"

[build-dependencies]
capnpc = "0.7.1"
rustc_version = "0.1.7"

[dependencies]
yaml-rust = "0.3.2"
filetime = "0.1.10"
lz4 = "1.16.131"
libc = "0.2.11"
petgraph = "0.2.7"
xml-rs = "0.3.2"
rand = "0.3.14"
uuid = { version = "0.2.2", features = ["v4"] }
tempdir = "0.3.4"
num_cpus = "0.2.12"
regex = "0.1.69"
lazy_static = "0.2.1"

log = "*"
fern = "*"
daemon = "*"
hyper = { version = "*", default-features = false, features = [""] }
iron = "*"
router = "*"
time = "*"
rustc-serialize = "*"

capnp = "0.7.1"

[target.'cfg(windows)'.dependencies]
winreg = "0.3.5"
winapi = "0.2.7"
kernel32-sys = "0.2.2"
version-sys = { version = "0.0.2", git = "https://github.com/bozaro/winapi-rs.git" }
