[package]
name = "octobuild"
build = "src/build.rs"
version = "0.0.11"
authors = [ "Artem V. Navrotskiy <bozaro@users.noreply.github.com>" ]

[profile.bench]
debug = true

[[bin]]
name = "octo_cl"
test = false

[[bin]]
name = "xgconsole"
test = false

[dependencies.lz4]
version = "*"

[dependencies.libc]
version = "*"

[dependencies.xml-rs]
version = "*"

[dependencies.uuid]
version = "*"

[dependencies.tempdir]
version = "*"
