[package]
name = "octobuild"
version = "0.0.2"
authors = [ "Artem V. Navrotskiy <bozaro@users.noreply.github.com>" ]

[dependencies.lz4]
version = "*"

[dependencies.xml-rs]
version = "*"

[dependencies.uuid]
version = "*"

[dependencies.winapi]
version = "*"

[dependencies.advapi32-sys]
version = "*"
