[package]
name = "octobuild"
build = "src/build.rs"
version = "0.1.9"
authors = [ "Artem V. Navrotskiy <bozaro@users.noreply.github.com>" ]

[profile.bench]
debug = true

[[bin]]
name = "octo_cl"

[[bin]]
name = "octo_clang"

[[bin]]
name = "octo_config"

[[bin]]
name = "xgConsole"

[build-dependencies]
rustc_version = "*"

[dependencies]
config = "*"
filetime = "*"
lz4 = "*"
libc = "*"
petgraph = "*"
xml-rs = "*"
rand = "*"
uuid = "*"
tempdir = "*"
num_cpus = "*"

[target.i686-pc-windows-gnu.dependencies]
winapi = "*"
kernel32-sys = "*"

[target.x86_64-pc-windows-gnu.dependencies]
winapi = "*"
kernel32-sys = "*"
