[package]
name = "octobuild"
build = "src/build.rs"
version = "0.1.15"
authors = [ "Artem V. Navrotskiy <bozaro@users.noreply.github.com>" ]
edition = "2018"

[profile.bench]
debug = true

[profile.release]
panic = "abort"
debug = true

[[bin]]
name = "octo_builder"

[[bin]]
name = "octo_cl"

[[bin]]
name = "octo_clang"

[[bin]]
name = "octo_coordinator"

[[bin]]
name = "xgConsole"

[[bin]]
name = "filter_cl"

[build-dependencies]
capnpc = "0.10"
rustc_version = "0.2"

[dependencies]
dirs= "2.0"
hostname = "0.1"
yaml-rust = "0.4"
filetime = "0.2"
lz4 = "1.23.0"
libc = "0.2"
petgraph = "0.4"
xml-rs = "0.8"
rand = "0.7"
uuid = { version = "0.7", features = ["v4"] }
tempdir = "0.3"
num_cpus = "1.10"
regex = "1.0"
lazy_static = "1.1"
clap = "2.33"
crossbeam = "0.7"
reqwest = "0.9"

byteorder = "1.2"
log = "0.4"
fern = "0.5"
daemon = "0.0.8"
nickel = "0.11"
hex = "0.3"
time = "0.1"
local-encoding = "0.2.0"
ipc = { git = "https://github.com/alexcrichton/ipc-rs" }

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

rust-crypto = { version = "0.2.35", git = "https://github.com/bozaro/rust-crypto.git", branch = "pr-364", default-features = false }
capnp = "0.10"

[target.'cfg(windows)'.dependencies]
winreg = "0.6"
winapi = { version = "0.3", features = ["winver"] }
