[package]
name = "octobuild"
build = "src/build.rs"
version = "0.1.13"
authors = [ "Artem V. Navrotskiy <bozaro@users.noreply.github.com>" ]

[profile.bench]
debug = true

[[bin]]
name = "octo_builder"

[[bin]]
name = "octo_cl"

[[bin]]
name = "octo_clang"

[[bin]]
name = "octo_coordinator"

[[bin]]
name = "xgConsole"

[build-dependencies]
capnpc = "0.7.1"
rustc_version = "0.1.7"

[dependencies]
yaml-rust = "0.3.3"
filetime = "0.1.10"
lz4 = "1.18.131"
libc = "0.2.12"
petgraph = "0.2.7"
xml-rs = "0.3.4"
rand = "0.3.14"
uuid = { version = "0.2.2", features = ["v4"] }
tempdir = "0.3.4"
num_cpus = "0.2.13"
regex = "0.1.71"
lazy_static = "0.2.1"

byteorder = "0.5.3"
log = "0.3.6"
fern = "0.3.5"
daemon = "0.0.7"
hyper = { version = "0.9.10", default-features = false, features = [""] }
nickel = { version = "0.8.1", git = "https://github.com/bozaro/nickel.rs.git", branch = "pr-334" }
router = "0.1.1"
time = "0.1.35"
rustc-serialize = "0.3.19"
local-encoding = "0.2.0"

rust-crypto = { version = "0.2.35", git = "https://github.com/bozaro/rust-crypto.git", branch = "pr-364", default-features = false, features = [""] }
capnp = "0.7.1"

[target.'cfg(windows)'.dependencies]
winreg = "0.3.5"
winapi = "0.2.7"
kernel32-sys = "0.2.2"
version-sys = { version = "0.0.1", git = "https://github.com/retep998/winapi-rs.git", rev = "bd08970c" }
