[package]
name = "octobuild"
version = "0.0.4"
authors = [ "Artem V. Navrotskiy <bozaro@users.noreply.github.com>" ]

[dependencies.daemon]
version = "*"

[dependencies.lz4]
version = "*"

[dependencies.xml-rs]
version = "*"

[dependencies.uuid]
version = "*"

[dependencies.tempdir]
version = "*"
